# Generated by Django 5.2.12 on 2026-04-07 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientesyMascotas', '0001_initial'),
        ('GestionServiciosyReserva', '0002_precioservicio_modalidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_programada', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('modalidad', models.CharField(choices=[('CLINICA', 'Clinica'), ('DOMICILIO', 'Domicilio')], max_length=20)),
                ('direccion_cita', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='GestionClientesyMascotas.mascota')),
                ('precio_servicio', models.ForeignKey(db_column='id_precio_servicio', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='GestionServiciosyReserva.precioservicio')),
                ('servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='GestionServiciosyReserva.servicio')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'cita',
            },
        ),
    ]
