from .servicios_view import ServicioListCreateView, ServicioDetailView
from .precioservicio_view import PrecioServicioListCreateView, PrecioServicioDetailView
from .categoriaservicio_view import CategoriaServicioListCreateView, CategoriaServicioDetailView
from .citas_view import CitaListCreateView, CitaDetailView, CitaEstadoUpdateView
