# Generated by Django 5.2.12 on 2026-04-07 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id_tipo_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Mascota',
                'verbose_name_plural': 'Tipos de Mascota',
                'db_table': 'tipo_mascota',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], max_length=10, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('tamano', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('notas_generales', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
                ('tipo_mascota', models.ForeignKey(db_column='id_tipo_mascota', on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='GestionClientesyMascotas.tipomascota')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascota',
            },
        ),
    ]
