# Generated by Django 5.2.12 on 2026-05-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionInventarioProveedores', '0003_enforce_not_null_veterinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='visible_catalogo',
            field=models.BooleanField(default=True),
        ),
    ]
