# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestionInventarioProveedores", "0004_producto_descripcion_producto_imagen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="tipo_mascota",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PERRO", "Perro"),
                    ("GATO", "Gato"),
                    ("AVE", "Ave"),
                    ("ROEDOR", "Roedor"),
                    ("PEZ", "Pez"),
                    ("OTRO", "Otro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="destacado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="producto",
            name="novedad_desde",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="novedad_hasta",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="tiene_promocion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="producto",
            name="tipo_descuento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PORCENTAJE", "Porcentaje"),
                    ("MONTO_FIJO", "Monto fijo"),
                    ("PRECIO_ESPECIAL", "Precio especial"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="porcentaje_descuento",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="monto_descuento",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_promocional",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="promocion_fecha_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="promocion_fecha_fin",
            field=models.DateField(blank=True, null=True),
        ),
    ]
