# Generated by Copilot on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestionInventarioProveedores", "0005_producto_catalogo_promocion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaproducto",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="categoriaproducto",
            constraint=models.UniqueConstraint(
                fields=["veterinaria", "nombre"],
                name="uq_categoria_producto_veterinaria_nombre",
            ),
        ),
    ]