# Generated by Codex on 2026-05-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_puntos_inventario(apps, schema_editor):
    Veterinaria = apps.get_model("AutenticacionySeguridad", "Veterinaria")
    PuntoInventario = apps.get_model("GestionInventarioProveedores", "PuntoInventario")
    UnidadMovil = apps.get_model("GestionServiciosyReserva", "UnidadMovil")
    UnidadMovilPunto = apps.get_model("GestionInventarioProveedores", "UnidadMovilPunto")

    for vet in Veterinaria.objects.filter(estado=True).only("id_veterinaria"):
        PuntoInventario.objects.get_or_create(
            veterinaria_id=vet.id_veterinaria,
            tipo="ALMACEN_GENERAL",
            nombre="Almacen General",
            defaults={"descripcion": "Punto creado automaticamente", "estado": True},
        )

    for unidad in UnidadMovil.objects.select_related("veterinaria").all():
        punto, _ = PuntoInventario.objects.get_or_create(
            veterinaria_id=unidad.veterinaria_id,
            tipo="UNIDAD_MOVIL",
            nombre=unidad.nombre,
            defaults={
                "descripcion": unidad.descripcion or "Unidad movil",
                "estado": unidad.estado,
            },
        )
        UnidadMovilPunto.objects.get_or_create(
            unidad_movil_id=unidad.id_unidad,
            defaults={
                "punto_inventario_id": punto.id_punto,
                "veterinaria_id": unidad.veterinaria_id,
                "estado": unidad.estado,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("GestionInventarioProveedores", "0005_producto_catalogo_promocion"),
        ("GestionServiciosyReserva", "0009_unidadmovilasignacion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PuntoInventario",
            fields=[
                ("id_punto", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ALMACEN_GENERAL", "Almacen general"),
                            ("SUCURSAL", "Sucursal"),
                            ("UNIDAD_MOVIL", "Unidad movil"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("estado", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "veterinaria",
                    models.ForeignKey(
                        db_column="id_veterinaria",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="puntos_inventario",
                        to="AutenticacionySeguridad.veterinaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Punto de inventario",
                "verbose_name_plural": "Puntos de inventario",
                "db_table": "punto_inventario",
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                ("id_movimiento", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA", "Salida"),
                            ("CONSUMO", "Consumo"),
                            ("REPOSICION", "Reposicion"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("DEVOLUCION", "Devolucion"),
                            ("AJUSTE", "Ajuste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cantidad_anterior", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("cantidad_posterior", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("motivo", models.TextField(blank=True, null=True)),
                ("fecha_movimiento", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        db_column="id_producto",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_inventario",
                        to="GestionInventarioProveedores.producto",
                    ),
                ),
                (
                    "punto_destino",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_punto_destino",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_entrada",
                        to="GestionInventarioProveedores.puntoinventario",
                    ),
                ),
                (
                    "punto_origen",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_punto_origen",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_salida",
                        to="GestionInventarioProveedores.puntoinventario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_inventario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "veterinaria",
                    models.ForeignKey(
                        db_column="id_veterinaria",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_inventario",
                        to="AutenticacionySeguridad.veterinaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de inventario",
                "verbose_name_plural": "Movimientos de inventario",
                "db_table": "movimiento_inventario",
            },
        ),
        migrations.CreateModel(
            name="StockPunto",
            fields=[
                ("id_stock", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("cantidad_minima", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "producto",
                    models.ForeignKey(
                        db_column="id_producto",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocks_por_punto",
                        to="GestionInventarioProveedores.producto",
                    ),
                ),
                (
                    "punto_inventario",
                    models.ForeignKey(
                        db_column="id_punto",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocks",
                        to="GestionInventarioProveedores.puntoinventario",
                    ),
                ),
                (
                    "veterinaria",
                    models.ForeignKey(
                        db_column="id_veterinaria",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocks_punto",
                        to="AutenticacionySeguridad.veterinaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock por punto",
                "verbose_name_plural": "Stocks por punto",
                "db_table": "stock_punto",
            },
        ),
        migrations.CreateModel(
            name="UnidadMovilPunto",
            fields=[
                ("id_unidad_movil_punto", models.AutoField(primary_key=True, serialize=False)),
                ("estado", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "punto_inventario",
                    models.OneToOneField(
                        db_column="id_punto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidad_movil_link",
                        to="GestionInventarioProveedores.puntoinventario",
                    ),
                ),
                (
                    "unidad_movil",
                    models.OneToOneField(
                        db_column="id_unidad",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario_punto",
                        to="GestionServiciosyReserva.unidadmovil",
                    ),
                ),
                (
                    "veterinaria",
                    models.ForeignKey(
                        db_column="id_veterinaria",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unidades_moviles_punto",
                        to="AutenticacionySeguridad.veterinaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vinculo unidad movil punto inventario",
                "verbose_name_plural": "Vinculos unidad movil punto inventario",
                "db_table": "unidad_movil_punto",
            },
        ),
        migrations.AddConstraint(
            model_name="movimientoinventario",
            constraint=models.CheckConstraint(
                condition=models.Q(cantidad__gt=0),
                name="chk_movimiento_cantidad_mayor_cero",
            ),
        ),
        migrations.AddConstraint(
            model_name="puntoinventario",
            constraint=models.UniqueConstraint(
                fields=("veterinaria", "tipo", "nombre"),
                name="uq_punto_inventario_veterinaria_tipo_nombre",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockpunto",
            constraint=models.UniqueConstraint(
                fields=("punto_inventario", "producto"),
                name="uq_stock_punto_producto",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockpunto",
            constraint=models.CheckConstraint(
                condition=models.Q(cantidad__gte=0),
                name="chk_stock_punto_cantidad_no_negativa",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockpunto",
            constraint=models.CheckConstraint(
                condition=models.Q(cantidad_minima__gte=0),
                name="chk_stock_punto_cantidad_minima_no_negativa",
            ),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(fields=["veterinaria", "fecha_movimiento"], name="idx_mov_tenant_fecha"),
        ),
        migrations.AddIndex(
            model_name="stockpunto",
            index=models.Index(fields=["veterinaria", "producto"], name="idx_stock_tenant_prod"),
        ),
        migrations.RunPython(seed_puntos_inventario, migrations.RunPython.noop),
    ]
