# Generated by Copilot on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestionInventarioProveedores", "0006_categoria_producto_unique_por_veterinaria"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.UniqueConstraint(
                fields=["veterinaria", "nombre", "categoria_producto"],
                name="uq_producto_veterinaria_nombre_categoria",
            ),
        ),
        migrations.AddConstraint(
            model_name="proveedor",
            constraint=models.UniqueConstraint(
                fields=["veterinaria", "nombre"],
                name="uq_proveedor_veterinaria_nombre",
            ),
        ),
    ]