# Generated by Django 5.2.12 on 2026-06-01 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AutenticacionySeguridad', '0025_alter_backupconfig_dias_retención_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(max_length=100)),
                ('origen', models.CharField(choices=[('ESTATICO', 'Estático'), ('DINAMICO', 'Dinámico')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('filtros', models.JSONField(blank=True, null=True)),
                ('columnas', models.JSONField(blank=True, null=True)),
                ('datos', models.JSONField(blank=True, null=True)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('HTML', 'HTML')], max_length=10)),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado'), ('ERROR', 'Error')], max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
                ('veterinaria', models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'db_table': 'reporte_generado',
            },
        ),
    ]
