# Generated by Django 5.2.12 on 2026-04-19 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionClientesyMascotas', '0001_initial'),
        ('GestionInventarioProveedores', '0001_initial'),
        ('GestionServiciosyReserva', '0003_cita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaClinica',
            fields=[
                ('id_consulta_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_consulta', models.TextField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_consulta', models.DateTimeField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('frecuencia_cardiaca', models.PositiveIntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.PositiveIntegerField(blank=True, null=True)),
                ('proxima_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('cita', models.ForeignKey(blank=True, db_column='id_cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_clinicas', to='GestionServiciosyReserva.cita')),
                ('usuario_veterinario', models.ForeignKey(db_column='id_usuario_veterinario', on_delete=django.db.models.deletion.PROTECT, related_name='consultas_veterinarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta clínica',
                'verbose_name_plural': 'Consultas clínicas',
                'db_table': 'consulta_clinica',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoClinico',
            fields=[
                ('id_archivo_clinico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='historial_clinico/')),
                ('tipo_archivo', models.CharField(choices=[('IMAGEN', 'Imagen'), ('PDF', 'PDF'), ('WORD', 'Word'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('consulta_clinica', models.ForeignKey(db_column='id_consulta_clinica', on_delete=django.db.models.deletion.CASCADE, related_name='archivos_clinicos', to='GestionarClinicaVeterinaria.consultaclinica')),
            ],
            options={
                'verbose_name': 'Archivo clínico',
                'verbose_name_plural': 'Archivos clínicos',
                'db_table': 'archivo_clinico',
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id_historial_clinico', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('mascota', models.OneToOneField(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, related_name='historial_clinico', to='GestionClientesyMascotas.mascota')),
            ],
            options={
                'verbose_name': 'Historial clínico',
                'verbose_name_plural': 'Historiales clínicos',
                'db_table': 'historial_clinico',
            },
        ),
        migrations.AddField(
            model_name='consultaclinica',
            name='historial_clinico',
            field=models.ForeignKey(db_column='id_historial_clinico', on_delete=django.db.models.deletion.CASCADE, related_name='consultas_clinicas', to='GestionarClinicaVeterinaria.historialclinico'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('consulta_clinica', models.OneToOneField(db_column='id_consulta_clinica', on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='GestionarClinicaVeterinaria.consultaclinica')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'receta',
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id_detalle_receta', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(max_length=150)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion_dias', models.PositiveIntegerField()),
                ('indicaciones_adicionales', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_receta', to='GestionInventarioProveedores.producto')),
                ('receta', models.ForeignKey(db_column='id_receta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='GestionarClinicaVeterinaria.receta')),
            ],
            options={
                'verbose_name': 'Detalle de receta',
                'verbose_name_plural': 'Detalles de receta',
                'db_table': 'detalle_receta',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('PROCEDIMIENTO', 'Procedimiento'), ('TERAPIA', 'Terapia'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado_tratamiento', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('consulta_clinica', models.ForeignKey(db_column='id_consulta_clinica', on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='GestionarClinicaVeterinaria.consultaclinica')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'db_table': 'tratamiento',
            },
        ),
        migrations.CreateModel(
            name='VacunaAplicada',
            fields=[
                ('id_vacuna_aplicada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('dosis', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_aplicada', models.DateField()),
                ('fecha_proxima', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_vacuna', models.CharField(choices=[('APLICADA', 'Aplicada'), ('PENDIENTE', 'Pendiente'), ('REFUERZO', 'Refuerzo')], default='APLICADA', max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('consulta_clinica', models.ForeignKey(db_column='id_consulta_clinica', on_delete=django.db.models.deletion.CASCADE, related_name='vacunas_aplicadas', to='GestionarClinicaVeterinaria.consultaclinica')),
            ],
            options={
                'verbose_name': 'Vacuna aplicada',
                'verbose_name_plural': 'Vacunas aplicadas',
                'db_table': 'vacuna_aplicada',
            },
        ),
    ]
