# Generated by Django 5.2.12 on 2026-05-12 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0013_alter_rol_nombre'),
        ('NotificacionesySeguimiento', '0002_alter_seguimiento_tipo_seguimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoUsuario',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('token_fcm', models.TextField(unique=True)),
                ('plataforma', models.CharField(choices=[('WEB', 'Navegador Web'), ('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL)),
                ('veterinaria', models.ForeignKey(db_column='id_veterinaria', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Dispositivo de Usuario',
                'verbose_name_plural': 'Dispositivos de Usuario',
                'db_table': 'dispositivo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('RESERVA', 'Reserva'), ('VACUNA', 'Vacuna'), ('CONTROL', 'Control Clínico'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('LEIDA', 'Leída'), ('FALLIDA', 'Fallida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('id_entidad_relacionada', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('veterinaria', models.ForeignKey(db_column='id_veterinaria', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(choices=[('RESERVA', 'Reserva de Cita'), ('VACUNA', 'Recordatorio de Vacuna'), ('CONTROL', 'Control Clínico')], max_length=20)),
                ('dias_anticipacion', models.IntegerField(default=1)),
                ('canales_habilitados', models.JSONField(default=dict, help_text="Ej: {'email': true, 'push': true, 'web': true}")),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('veterinaria', models.ForeignKey(db_column='id_veterinaria', on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_notificacion', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificación',
                'db_table': 'configuracion_notificacion',
                'unique_together': {('veterinaria', 'tipo_notificacion')},
            },
        ),
    ]
