# Generated by Django 5.2.12 on 2026-05-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotificacionesySeguimiento', '0003_dispositivousuario_notificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
