# Generated by Codex on 2026-05-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AutenticacionySeguridad", "0024_billingdemoevent_stripe_fields_and_statuses"),
        ("GestionClientesyMascotas", "0004_alter_mascota_especie_remove_raza_especie_and_more"),
        ("GestionInventarioProveedores", "0008_producto_proveedor_uniques_y_validaciones"),
        ("GestionServiciosyReserva", "0009_unidadmovilasignacion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("id_venta", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_venta", models.DateTimeField(auto_now_add=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "estado_venta",
                    models.CharField(
                        choices=[("PENDIENTE_COBRO", "Pendiente de cobro"), ("ANULADA", "Anulada")],
                        default="PENDIENTE_COBRO",
                        max_length=20,
                    ),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                ("estado", models.BooleanField(default=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cliente",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas_como_cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_mascota",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to="GestionClientesyMascotas.mascota",
                    ),
                ),
                (
                    "usuario_responsable",
                    models.ForeignKey(
                        db_column="id_usuario_responsable",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "veterinaria",
                    models.ForeignKey(
                        db_column="id_veterinaria",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to="AutenticacionySeguridad.veterinaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "db_table": "venta",
            },
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                ("id_detalle_venta", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_item",
                    models.CharField(choices=[("PRODUCTO", "Producto"), ("SERVICIO", "Servicio")], max_length=10),
                ),
                ("descripcion_item", models.CharField(max_length=255)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=12)),
                ("precio_unitario", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("observacion", models.TextField(blank=True, null=True)),
                ("estado", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "precio_servicio",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_precio_servicio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_venta",
                        to="GestionServiciosyReserva.precioservicio",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_producto",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_venta",
                        to="GestionInventarioProveedores.producto",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_servicio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_venta",
                        to="GestionServiciosyReserva.servicio",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        db_column="id_venta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="GestiondeVentasyPagos.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de venta",
                "verbose_name_plural": "Detalles de venta",
                "db_table": "detalle_venta",
            },
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(fields=["veterinaria", "fecha_venta"], name="idx_venta_tenant_fecha"),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(fields=["veterinaria", "estado_venta"], name="idx_venta_tenant_estado"),
        ),
        migrations.AddConstraint(
            model_name="detalleventa",
            constraint=models.CheckConstraint(
                condition=models.Q(cantidad__gt=0),
                name="chk_detalle_venta_cantidad_mayor_cero",
            ),
        ),
        migrations.AddConstraint(
            model_name="detalleventa",
            constraint=models.CheckConstraint(
                condition=models.Q(precio_unitario__gt=0),
                name="chk_detalle_venta_precio_mayor_cero",
            ),
        ),
        migrations.AddConstraint(
            model_name="detalleventa",
            constraint=models.CheckConstraint(
                condition=models.Q(subtotal__gte=0),
                name="chk_detalle_venta_subtotal_no_negativo",
            ),
        ),
    ]
