# Generated by Codex on 2026-05-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AutenticacionySeguridad", "0024_billingdemoevent_stripe_fields_and_statuses"),
        ("GestionClientesyMascotas", "0004_alter_mascota_especie_remove_raza_especie_and_more"),
        ("GestionInventarioProveedores", "0008_producto_proveedor_uniques_y_validaciones"),
        ("GestionServiciosyReserva", "0009_unidadmovilasignacion_and_more"),
        ("GestiondeVentasyPagos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarritoTemporal",
            fields=[
                ("id_carrito", models.AutoField(primary_key=True, serialize=False)),
                (
                    "estado_carrito",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("VACIADO", "Vaciado")],
                        default="ACTIVO",
                        max_length=10,
                    ),
                ),
                ("subtotal_estimado", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total_estimado", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("estado", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="id_cliente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carritos_temporales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "veterinaria",
                    models.ForeignKey(
                        db_column="id_veterinaria",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carritos_temporales",
                        to="AutenticacionySeguridad.veterinaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrito temporal",
                "verbose_name_plural": "Carritos temporales",
                "db_table": "carrito_temporal",
            },
        ),
        migrations.CreateModel(
            name="DetalleCarritoTemporal",
            fields=[
                ("id_detalle_carrito", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_item",
                    models.CharField(choices=[("PRODUCTO", "Producto"), ("SERVICIO", "Servicio")], max_length=10),
                ),
                ("descripcion_item", models.CharField(max_length=255)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=12)),
                ("precio_unitario_estimado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subtotal_estimado", models.DecimalField(decimal_places=2, max_digits=12)),
                ("observacion", models.TextField(blank=True, null=True)),
                ("estado", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "carrito",
                    models.ForeignKey(
                        db_column="id_carrito",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="GestiondeVentasyPagos.carritotemporal",
                    ),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_mascota",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_carrito",
                        to="GestionClientesyMascotas.mascota",
                    ),
                ),
                (
                    "precio_servicio",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_precio_servicio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_carrito",
                        to="GestionServiciosyReserva.precioservicio",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_producto",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_carrito",
                        to="GestionInventarioProveedores.producto",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_servicio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_carrito",
                        to="GestionServiciosyReserva.servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de carrito temporal",
                "verbose_name_plural": "Detalles de carrito temporal",
                "db_table": "detalle_carrito_temporal",
            },
        ),
        migrations.AddIndex(
            model_name="carritotemporal",
            index=models.Index(fields=["veterinaria", "cliente", "estado_carrito"], name="idx_cart_tenant_cli_est"),
        ),
        migrations.AddIndex(
            model_name="carritotemporal",
            index=models.Index(fields=["veterinaria", "fecha_creacion"], name="idx_cart_tenant_fecha"),
        ),
        migrations.AddConstraint(
            model_name="carritotemporal",
            constraint=models.UniqueConstraint(
                condition=models.Q(estado=True, estado_carrito="ACTIVO"),
                fields=("veterinaria", "cliente"),
                name="uq_cart_active_tenant_client",
            ),
        ),
        migrations.AddConstraint(
            model_name="carritotemporal",
            constraint=models.CheckConstraint(
                condition=models.Q(subtotal_estimado__gte=0),
                name="chk_cart_subtotal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="carritotemporal",
            constraint=models.CheckConstraint(
                condition=models.Q(total_estimado__gte=0),
                name="chk_cart_total_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="detallecarritotemporal",
            constraint=models.CheckConstraint(
                condition=models.Q(cantidad__gt=0),
                name="chk_detail_cart_quantity_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="detallecarritotemporal",
            constraint=models.CheckConstraint(
                condition=models.Q(precio_unitario_estimado__gte=0),
                name="chk_detail_cart_unit_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="detallecarritotemporal",
            constraint=models.CheckConstraint(
                condition=models.Q(subtotal_estimado__gte=0),
                name="chk_detail_cart_subtotal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="detallecarritotemporal",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        mascota__isnull=True,
                        precio_servicio__isnull=True,
                        producto__isnull=False,
                        servicio__isnull=True,
                        tipo_item="PRODUCTO",
                    )
                    | models.Q(
                        mascota__isnull=False,
                        precio_servicio__isnull=False,
                        producto__isnull=True,
                        servicio__isnull=False,
                        tipo_item="SERVICIO",
                    )
                ),
                name="chk_detail_cart_type_consistency",
            ),
        ),
    ]
