# Generated by Django 5.2.12 on 2026-06-17 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0025_alter_backupconfig_dias_retención_and_more'),
        ('GestiondeVentasyPagos', '0002_carrito_temporal_and_detalle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado_venta',
            field=models.CharField(choices=[('PENDIENTE_COBRO', 'Pendiente de cobro'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE_COBRO', max_length=20),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_referencia', models.CharField(choices=[('VENTA_WEB', 'Venta registrada desde Web'), ('PEDIDO_MOVIL', 'Pedido de productos desde Móvil'), ('CITA_SERVICIO', 'Cita o servicio veterinario'), ('SAAS_SUSCRIPCION', 'Suscripción SaaS')], max_length=30)),
                ('referencia_id', models.IntegerField()),
                ('metodo_pago', models.CharField(choices=[('STRIPE', 'Stripe'), ('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('QR', 'QR'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado'), ('FALLIDO', 'Fallido'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_transaccion', models.CharField(blank=True, max_length=120, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_como_cliente', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
                ('veterinaria', models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('numero_comprobante', models.CharField(max_length=50)),
                ('tipo_comprobante', models.CharField(choices=[('FACTURA', 'Factura'), ('RECIBO', 'Recibo')], default='RECIBO', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('detalle_items', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('EMITIDO', 'Emitido'), ('ANULADO', 'Anulado')], default='EMITIDO', max_length=20)),
                ('url_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('veterinaria', models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='AutenticacionySeguridad.veterinaria')),
                ('pago', models.OneToOneField(db_column='id_pago', on_delete=django.db.models.deletion.PROTECT, related_name='comprobante', to='GestiondeVentasyPagos.pago')),
            ],
            options={
                'verbose_name': 'Comprobante de pago',
                'verbose_name_plural': 'Comprobantes de pago',
                'db_table': 'comprobante_pago',
            },
        ),
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='GestiondeVentasyPagos.pago')),
                ('veterinaria', models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_pago', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Transacción de pago',
                'verbose_name_plural': 'Transacciones de pago',
                'db_table': 'transaccion_pago',
            },
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['veterinaria', 'tipo_referencia', 'referencia_id'], name='pago_id_vete_5995cf_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['stripe_session_id'], name='pago_stripe__8b0597_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobantepago',
            index=models.Index(fields=['veterinaria', 'numero_comprobante'], name='comprobante_id_vete_9d0bd1_idx'),
        ),
    ]
