# Generated by Django 5.2.12 on 2026-04-08 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0002_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='fecha_hora', help_text='Fecha y hora en que ocurrió el evento.')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FALLIDO', 'Inicio de sesión fallido'), ('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('VISUALIZAR', 'Visualizar'), ('EXPORTAR', 'Exportar'), ('CAMBIO_PASSWORD', 'Cambio de contraseña'), ('CAMBIO_PERMISOS', 'Cambio de permisos'), ('ACCESO_DENEGADO', 'Acceso denegado'), ('ACTIVAR', 'Activar'), ('DESACTIVAR', 'Desactivar')], help_text='Acción realizada en el sistema.', max_length=50)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción legible del evento.')),
                ('ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se originó la acción.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Información del navegador o cliente.')),
                ('modulo', models.CharField(blank=True, choices=[('autenticacion', 'Autenticación'), ('usuarios', 'Usuarios'), ('perfiles', 'Perfiles'), ('roles', 'Roles'), ('permisos', 'Permisos'), ('bitacora', 'Bitácora'), ('sistema', 'Sistema')], default='', help_text='Módulo del sistema donde ocurrió el evento.', max_length=100)),
                ('entidad_tipo', models.CharField(blank=True, default='', help_text='Tipo de entidad afectada. Ejemplo: Usuario, Herramienta, Prestamo.', max_length=100)),
                ('entidad_id', models.CharField(blank=True, default='', help_text='Identificador de la entidad afectada.', max_length=50)),
                ('resultado', models.CharField(choices=[('EXITO', 'Éxito'), ('FALLO', 'Fallo')], default='EXITO', help_text='Resultado del evento.', max_length=10)),
                ('metadatos', models.JSONField(blank=True, default=dict, help_text='Información adicional del evento en formato JSON.')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', help_text='Usuario que ejecutó la acción. Puede ser nulo para eventos del sistema o anónimos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácora',
                'db_table': 'bitacora',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora'], name='bitacora_fecha_h_979090_idx'), models.Index(fields=['accion'], name='bitacora_accion_401835_idx'), models.Index(fields=['resultado'], name='bitacora_resulta_f6806c_idx'), models.Index(fields=['modulo'], name='bitacora_modulo_298c06_idx')],
            },
        ),
    ]
