# Generated by Django 5.2.12 on 2026-04-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0003_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='modulo',
            field=models.CharField(blank=True, choices=[('autenticacion', 'Autenticación'), ('usuarios', 'Usuarios'), ('perfiles', 'Perfiles'), ('roles', 'Roles'), ('permisos', 'Permisos'), ('bitacora', 'Bitácora'), ('sistema', 'Sistema')], default='sistema', help_text='Módulo del sistema donde ocurrió el evento.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['usuario', 'fecha_hora'], name='bitacora_id_usua_4e574c_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['entidad_tipo', 'entidad_id'], name='bitacora_entidad_d34b25_idx'),
        ),
    ]
