# Generated by Django 5.2.12 on 2026-05-06 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0010_alter_bitacora_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupousuario',
            name='es_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupousuario',
            name='rol_base',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='permite_auto_registro_clientes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='veterinaria',
            field=models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='AutenticacionySeguridad.veterinaria'),
        ),
    ]
