# Generated by Django 5.2.12 on 2026-05-06 21:34

import apps.AutenticacionySeguridad.models.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0011_grupousuario_es_base_grupousuario_rol_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='payload',
            field=apps.AutenticacionySeguridad.models.encrypted_fields.EncryptedJSONField(),
        ),
    ]
