# Generated by Django 5.2.12 on 2026-05-10 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0009_backupconfig'),
        ('AutenticacionySeguridad', '0013_alter_rol_nombre'),
    ]

    operations = [
    ]
