# Generated by Copilot on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AutenticacionySeguridad", "0015_backupconfig_add_custom_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupconfig",
            name="minuto_ejecucion",
            field=models.IntegerField(default=15, help_text="Minuto del día 0-59"),
        ),
    ]
