# Generated by Copilot on 2026-05-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AutenticacionySeguridad", "0014_user_bloqueado_hasta_user_intentos_fallidos_and_more"),
        ("AutenticacionySeguridad", "0016_backupconfig_minuto_ejecucion"),
    ]

    operations = []
