# Generated by Django 5.2.12 on 2026-05-24 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0021_alter_grupousuario_veterinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='owner_user',
            field=models.ForeignKey(blank=True, db_column='owner_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veterinarias_propietarias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BillingDemoEvent',
            fields=[
                ('id_billing_demo_event', models.AutoField(primary_key=True, serialize=False)),
                ('checkout_token', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(choices=[('DIRECT_PURCHASE', 'Compra directa'), ('TRIAL_UPGRADE', 'Upgrade desde prueba')], max_length=30)),
                ('status', models.CharField(choices=[('STARTED', 'Iniciado'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='STARTED', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payment_mode', models.CharField(default='DEMO', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.PROTECT, related_name='billing_demo_events', to='AutenticacionySeguridad.plansuscripcion')),
                ('user', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_demo_events', to=settings.AUTH_USER_MODEL)),
                ('veterinaria', models.ForeignKey(blank=True, db_column='id_veterinaria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_demo_events', to='AutenticacionySeguridad.veterinaria')),
            ],
            options={
                'verbose_name': 'Evento de facturacion demo',
                'verbose_name_plural': 'Eventos de facturacion demo',
                'db_table': 'billing_demo_event',
                'indexes': [models.Index(fields=['status', 'event_type'], name='billing_dem_status_e4f3c0_idx'), models.Index(fields=['expires_at'], name='billing_dem_expires_2eeede_idx')],
            },
        ),
    ]
