# Generated by Django 5.2.12 on 2026-06-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionySeguridad', '0024_billingdemoevent_stripe_fields_and_statuses'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='backupconfig',
                    name='dias_retención',
                    field=models.IntegerField(db_column='dias_retención', default=30),
                ),
                migrations.AlterField(
                    model_name='backupconfig',
                    name='próximo_backup_programado',
                    field=models.DateTimeField(blank=True, db_column='próximo_backup_programado', null=True),
                ),
                migrations.AlterField(
                    model_name='backupconfig',
                    name='último_backup',
                    field=models.DateTimeField(blank=True, db_column='último_backup', null=True),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='billingdemoevent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('STARTED', 'Iniciado'), ('PAID', 'Pagado'), ('CONFIRMED', 'Confirmado'), ('FAILED', 'Fallido'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado')], default='STARTED', max_length=20),
        ),
    ]
