# Generated by Django 5.2.12 on 2026-06-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AutenticacionySeguridad", "0025_alter_backupconfig_dias_retención_and_more"),
    ]

    operations = [
        # Revert the `status` choices on BillingDemoEvent to the previous set
        migrations.AlterField(
            model_name='billingdemoevent',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Iniciado'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='STARTED', max_length=20),
        ),
    ]
